# Generated by Django 4.0.3 on 2022-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Gallery',
        ),
    ]
