# Generated by Django 4.0.3 on 2022-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
